### ISSUE TITLE
Add MINLPTests

### ISSUE THREAD

**Issue by odow** [MAiNGO-github/MAiNGO.jl#3]
See, e.g., https://github.com/jump-dev/AmplNLWriter.jl/blob/master/test/MINLPTests

I can help with this

**Comment by MAiNGO-github** [comment]
Cool package. I used the simple examples from Baron.jl, but more tests are certainly welcome.

I tested this locally, however, many tests have unbounded domain or other things that are problematic for deterministic global optimization (a prime example would be nlp_002_010). Adding reasonable bounds on the variables would help. But maybe you also want to have some tests for solvers that can't handle any constraints?

```
# nlp/001_010 002_010 008_010 008_011 009_010 009_011: domain unbounded, 002_010 even negative log
# nlp/005_010     : inv with possible zero in range 
# nlp/005_011     : Using division
# nlp-cvx/109_010 : Even Ipopt fails to converge
# nlp-cvx/105_01x : log with possible negative value in range
# nlp-cvx/204_010 : inv with possible zero in range
# nlp-cvx/205_010 : inv with possible zero in range
# nlp-mi/001_010 002_010: domain unbounded
# nlp-mi/005_010  : inv with possible zero in range 
# nlp-mi/006_010  : user defined function
```

do you think there will be an update that might introduce bounds to more problems?

**Comment by odow** [comment]
We could add more test cases reasonable variable bounds. We probably want to keep the unbounded ones. It's nice to test if solvers would detect unbounded domains and return an appropriate status.

cc @ccoffrin

**Comment by MAiNGO-github** [comment]
Best case would be if there existed something like `MOI.supports(::Optimizer, ::MOI.UnboundedDomain) = true` even if it was only taking into account variable bounds.
We currently do not detect this, but rather use default bounds.
